import { z } from "zod";
export declare const userProfile: z.ZodObject<{
    id: z.ZodString;
    organizationId: z.ZodNullable<z.ZodString>;
    userId: z.ZodString;
    firstName: z.ZodString;
    lastName: z.ZodNullable<z.ZodString>;
    currentPosition: z.ZodNullable<z.ZodString>;
    DOB: z.ZodNullable<z.ZodString>;
    currentWorkplace: z.ZodNullable<z.ZodString>;
    description: z.ZodNullable<z.ZodString>;
    additionalInfo: z.ZodNullable<z.ZodString>;
    tagline: z.ZodNullable<z.ZodString>;
    headline: z.ZodNullable<z.ZodString>;
    about: z.ZodNullable<z.ZodString>;
    location: z.ZodNullable<z.ZodString>;
    profilePhotoUrl: z.ZodNullable<z.ZodString>;
    bannerPhotoUrl: z.ZodNullable<z.ZodString>;
    website: z.ZodNullable<z.ZodString>;
    linkedinUrl: z.ZodNullable<z.ZodString>;
    githubUrl: z.ZodNullable<z.ZodString>;
    portfolioUrl: z.ZodNullable<z.ZodString>;
    updatedAt: z.ZodNullable<z.ZodCoercedDate<unknown>>;
    createdAt: z.ZodNullable<z.ZodCoercedDate<unknown>>;
}, z.core.$strip>;
export declare const userProfileInsertSchema: z.ZodObject<{
    description: z.ZodNullable<z.ZodString>;
    website: z.ZodNullable<z.ZodString>;
    location: z.ZodNullable<z.ZodString>;
    firstName: z.ZodString;
    lastName: z.ZodNullable<z.ZodString>;
    currentPosition: z.ZodNullable<z.ZodString>;
    DOB: z.ZodNullable<z.ZodString>;
    currentWorkplace: z.ZodNullable<z.ZodString>;
    additionalInfo: z.ZodNullable<z.ZodString>;
    tagline: z.ZodNullable<z.ZodString>;
    headline: z.ZodNullable<z.ZodString>;
    about: z.ZodNullable<z.ZodString>;
    profilePhotoUrl: z.ZodNullable<z.ZodString>;
    bannerPhotoUrl: z.ZodNullable<z.ZodString>;
    linkedinUrl: z.ZodNullable<z.ZodString>;
    githubUrl: z.ZodNullable<z.ZodString>;
    portfolioUrl: z.ZodNullable<z.ZodString>;
}, z.core.$strip>;
export declare const userProfileUpdateSchema: z.ZodObject<{
    description: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    website: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    location: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    firstName: z.ZodOptional<z.ZodString>;
    lastName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    currentPosition: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    DOB: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    currentWorkplace: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    additionalInfo: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    tagline: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    headline: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    about: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    profilePhotoUrl: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    bannerPhotoUrl: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    linkedinUrl: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    githubUrl: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    portfolioUrl: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, z.core.$strip>;
export type UserProfileUpdateType = z.infer<typeof userProfileUpdateSchema>;
export type UserProfile = z.infer<typeof userProfile>;
export type UserProfileInsertType = z.infer<typeof userProfileInsertSchema>;
